apiVersion: apps/v1
kind: Deployment
metadata:
  name: contenedor1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contenedor1
  template:
    metadata:
      labels:
        app: contenedor1
    spec:
      containers:
      - name: contenedor1
        image: contenedor1:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "256Mi"
            cpu: "700m"
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: contenedor1
spec:
  selector:
    app: contenedor1
  ports:
  - port: 6000
    targetPort: 8000
  externalTrafficPolicy: Local
  type: LoadBalancer
        
